# genetic loci_pattern, file_name, loci_pattern(before/after) word 추출

In [ ]:
import os
import re

def extract_context(text, loci, window_size=20):
  # 입력된 텍스트를 공백을 기준으로 분할하여 단어 목록 생성
    words = text.split()
    # enumerate : 인자로 넘어온 목록을 기준으로 인덱스와 원소를 차례대로 접근하게 해주는 반복자(iterator) 객체를 반환해주는 함수
    # 단어 목록을 순회하면서, 각 단어와 그 위치 i를 가지고 오기
    for i, word in enumerate(words):
        if loci in word:
          # 현재 단어의 위치에서 window_size만큼 앞으로 간 위치를 계산, 이 값이 0보다 작지 않도록 하기
            start = max(0, i - window_size)
            # 현재 단어의 위치에서 window_size만큼 뒤로 간 위치를 계산하되, 이 값이 전체 단어 수를 초과하지 않도록 하기
            end = min(len(words), i + window_size + 1)
            return ' '.join(words[start:i]), ' '.join(words[i+1:end])
    return "", ""

# 데이터 파일 경로
text_folder_path = 'C:/Users/jhang/FullText_Epigenomics_data240126'

# loci_pattern의 패턴 지정
loci_pattern = re.compile(r'\d+[pq]\d+(\.\d+)?')

# 찾은 모든 위치, 파일 이름, 제목 및 컨텍스트 저장
all_data = []

for file_name in os.listdir(text_folder_path):
    # endswith() : 메서드 사용하여 어떤 문자열에서 특정 문자열로 끝나는지 확인 후, 그 결과 true 혹은 false 로 반환
    if file_name.endswith('.txt'):
        file_path = os.path.join(text_folder_path, file_name)
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()

            for match in loci_pattern.finditer(text):
                loci = match.group()
                before, after = extract_context(text, loci)
                all_data.append((file_name, loci, before, after))

# 찾은 file_name, loci, before, after 출력
for file_name, loci, before, after in all_data:
    print(f"File: {file_name}, Loci: {loci}")
    print(f"Words before: {before}")
    print(f"Words after: {after}\n")

File: pmc_10001080.txt, Loci: 18q21.33
Words before: enzyme used (regions of the CpG islands of the SBNO2, LINC00493, and CLDND1 genes and the intergenic CpG-island on chromosome
Words after: The DCs were selected from 5 genome regions, each containing 2 restriction enzyme recognition sites and nonmethylated both in normal

File: pmc_10006236.txt, Loci: 12p13.33
Words before: Proc. Natl. Acad. Sci. U. S. A. 2014 111 E645 654 10.1073/pnas.1312523111 24469817 66. Shi J Inherited variation at chromosome
Words after: including RAD52, influences the risk of squamous cell lung carcinoma Cancer Discov. 2012 2 131 139 10.1158/2159-8290.CD-11-0246 22585858 67. Ihsan

File: pmc_10008685.txt, Loci: 19p1036
Words before: Biol Sci Int J Biol Sci ijbs International Journal of Biological Sciences 1449-2288 Ivyspring International Publisher Sydney 36923930 10008685 10.7150/ijbs.78535
Words after: Review The Emerging Role of Super-enhancers as Therapeutic Targets in The Digestive System Tumors Li Xiang-Ping 1 2 * Qu

File: pmc_10010017.txt, Loci: 14q32.1
Words before: piRNAs were upregulated (has-piR-010894-3 and has-piR-001168-4) [97]. Previous studies have found that the dysregulation of the DLK1-DIO3 locus on chromosomes
Words after: was related to the development of respiratory tract diseases (including cancer). Katey SS Enfield et al. analyzed the piRNAs encoded

File: pmc_10010017.txt, Loci: 14q32.31
Words before: piRNAs were upregulated (has-piR-010894-3 and has-piR-001168-4) [97]. Previous studies have found that the dysregulation of the DLK1-DIO3 locus on chromosomes
Words after: was related to the development of respiratory tract diseases (including cancer). Katey SS Enfield et al. analyzed the piRNAs encoded

File: pmc_10011137.txt, Loci: 1q45
Words before: 30https://ror.org/03zzw1w08grid.417467.70000 0004 0443 9942Division of Respiratory Medicine, Department of Internal Medicine, Center for Individualized Medicine, Mayo Clinic, Scottsdale, AZ USA
Words after: 0001 2168 186XDepartment of Medicine, University of Arizona, Tucson, AZ USA 32https://ror.org/05a0ya142grid.66859.34Broad Institute of MIT and Harvard, Cambridge, MA USA

File: pmc_10011137.txt, Loci: 415q13
Words before: Institute, Newcastle, New South Wales Australia 78https://ror.org/01dbmzx78grid.414659.b0000 0000 8828 1230Wal-yan Respiratory Research Centre, Telethon Kids Institute, Perth, Western Australia Australia
Words after: 0004 0375 4078School of Allied Health, Faculty of Health Sciences, Curtin University, Perth, Western Australia Australia 80https://ror.org/01nrxwf90grid.4305.20000 0004 1936 7988Lothian

File: pmc_10012557.txt, Loci: 12p70
Words before: M Deauvieau F Scuiller M Hiscott J Bates EE A type I interferon autocrine-paracrine loop is involved in toll-like receptor-induced
Words after: secretion by dendritic cells J Exp Med 2005 201 9 1435 46 10.1084/jem.20041964 15851485 57. Lee AJ Ashkar AA The

File: pmc_10014551.txt, Loci: 22q11.2
Words before: Prader-Willi syndrome, Williams syndrome, Fragile X syndrome, Angelman’s syndrome, Cri de Chat syndrome, Down syndrome, Lowe syndrome, Smith-Magenis, PTEN mutations,
Words after: deletion syndrome, obsessive compulsive disorder (OCD), Tic disorders, eating disorders, psychotic disorders, Attention deficit hyperactivity disorder (ADHD), RRBs often form

File: pmc_10014551.txt, Loci: 22q11.2
Words before: Prader-Willi syndrome, Williams syndrome, Fragile X syndrome, Angelman’s syndrome, Cri de Chat syndrome, Down syndrome, Lowe syndrome, Smith-Magenis, PTEN mutations,
Words after: deletion syndrome, obsessive compulsive disorder (OCD), Tic disorders, eating disorders, psychotic disorders, Attention deficit hyperactivity disorder (ADHD), RRBs often form

File: pmc_10014551.txt, Loci: 22q11.2
Words before: Prader-Willi syndrome, Williams syndrome, Fragile X syndrome, Angelman’s syndrome, Cri de Chat syndrome, Down syndrome, Lowe syndrome, Smith-Magenis, PTEN mutations,
Words after: deletion syndrome, obsessive compulsive disorder (OCD), Tic disorders, eating disorders, psychotic disorders, Attention deficit hyperactivity disorder (ADHD), RRBs often form

File: pmc_10014730.txt, Loci: 7q35
Words before: 5333361. 10.1155/2023/5333361 36644165 IsobeM.EriksonJ.EmanuelB. S.NowellP. C.CroceC. M. (1985). Location of gene for beta subunit of human T-cell receptor at band
Words after: a region prone to rearrangements in T cells. Science 228, 580–582. 10.1126/science.3983641 3983641 KeG.MengQ.FinleyT.WangT.ChenW.MaW. (2017). Lightgbm: A highly efficient gradient

File: pmc_10018228.txt, Loci: 8q24.21
Words before: gains or losses are associated with high grade, Gleason score, and PSA levels (47). Common amplifications span the oncogenes MYC
Words after: CCND1 (11q13.2), FCFR (12p11.21), and NSD3 (8p11.23) and common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1),

File: pmc_10018228.txt, Loci: 11q13.2
Words before: losses are associated with high grade, Gleason score, and PSA levels (47). Common amplifications span the oncogenes MYC (8q24.21), CCND1
Words after: FCFR (12p11.21), and NSD3 (8p11.23) and common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2

File: pmc_10018228.txt, Loci: 12p11.21
Words before: associated with high grade, Gleason score, and PSA levels (47). Common amplifications span the oncogenes MYC (8q24.21), CCND1 (11q13.2), FCFR
Words after: and NSD3 (8p11.23) and common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22),

File: pmc_10018228.txt, Loci: 8p11.23
Words before: grade, Gleason score, and PSA levels (47). Common amplifications span the oncogenes MYC (8q24.21), CCND1 (11q13.2), FCFR (12p11.21), and NSD3
Words after: and common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL

File: pmc_10018228.txt, Loci: 10q23
Words before: span the oncogenes MYC (8q24.21), CCND1 (11q13.2), FCFR (12p11.21), and NSD3 (8p11.23) and common deletions span tumor suppressor genes PTEN
Words after: TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), and FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors

File: pmc_10018228.txt, Loci: 17p13.1
Words before: oncogenes MYC (8q24.21), CCND1 (11q13.2), FCFR (12p11.21), and NSD3 (8p11.23) and common deletions span tumor suppressor genes PTEN (10q23), TP53
Words after: CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), and FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors with greater

File: pmc_10018228.txt, Loci: 12p13.1
Words before: (8q24.21), CCND1 (11q13.2), FCFR (12p11.21), and NSD3 (8p11.23) and common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B
Words after: MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), and FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors with greater mutational burden

File: pmc_10018228.txt, Loci: 5q11.2
Words before: (11q13.2), FCFR (12p11.21), and NSD3 (8p11.23) and common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1
Words after: & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), and FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors with greater mutational burden or with

File: pmc_10018228.txt, Loci: 3p26
Words before: NSD3 (8p11.23) and common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2
Words after: SPOPL (2q22.1), and FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors with greater mutational burden or with higher CNA frequencies have

File: pmc_10018228.txt, Loci: 2q22.1
Words before: and common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL
Words after: and FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors with greater mutational burden or with higher CNA frequencies have more mutations

File: pmc_10018228.txt, Loci: 3p13
Words before: span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), and FOXP1/RYBP/SHQ1
Words after: (47). Interestingly, aggressive prostate tumors with greater mutational burden or with higher CNA frequencies have more mutations at KMT2D, TP53,

File: pmc_10018228.txt, Loci: 1q23.1
Words before: cell growth and survival, and DNA replication, respectively. The study by Koga et al. identified a novel deletion spanning ETV3
Words after: another ETS transcription factor, in AA tumor samples (13). Overall, most of these studies addressing racial differences did not have

File: pmc_10023161.txt, Loci: 5q31
Words before: JacksonCE BeckmannJS SebounE 1998 Vocal cord and pharyngeal weakness with autosomal dominant distal myopathy: clinical description and gene localization to
Words after: American Journal of Human Genetics 63 1732 1742 10.1086/302166 9837826 FrancoD MeilhacSM ChristoffelsVM KispertA BuckinghamM KellyRG 2006 Left and right

File: pmc_10023161.txt, Loci: 5q31
Words before: JacksonCE BeckmannJS SebounE 1998 Vocal cord and pharyngeal weakness with autosomal dominant distal myopathy: clinical description and gene localization to
Words after: American Journal of Human Genetics 63 1732 1742 10.1086/302166 9837826 FrancoD MeilhacSM ChristoffelsVM KispertA BuckinghamM KellyRG 2006 Left and right

File: pmc_10026484.txt, Loci: 1p1
Words before: confirm the presence of the expected BCL7A mutations at the RNA level. Read counts per gene were obtained using htseq-count
Words after: with the following options: “-m intersection-nonempty -f bam -t exon -i gene_id -r pos -s reverse”. Further analyses were performed

File: pmc_10036404.txt, Loci: 14q32
Words before: maternally expressed gene mutually imprints with the paternally expressed gene delta-like homologue 1 (DLK1), forming an imprinting domain on chromosome
Words after: that contains two differentially methylated regions (DMRs), namely the intergenic DMR (IG-DMR) and post fertilization-derived secondary MEG3-DMR, as depicted in

File: pmc_10036404.txt, Loci: 14q32
Words before: maternally expressed gene mutually imprints with the paternally expressed gene delta-like homologue 1 (DLK1), forming an imprinting domain on chromosome
Words after: that contains two differentially methylated regions (DMRs), namely the intergenic DMR (IG-DMR) and post fertilization-derived secondary MEG3-DMR, as depicted in

File: pmc_10036404.txt, Loci: 14q32
Words before: maternally expressed gene mutually imprints with the paternally expressed gene delta-like homologue 1 (DLK1), forming an imprinting domain on chromosome
Words after: that contains two differentially methylated regions (DMRs), namely the intergenic DMR (IG-DMR) and post fertilization-derived secondary MEG3-DMR, as depicted in

File: pmc_10036404.txt, Loci: 14q32
Words before: maternally expressed gene mutually imprints with the paternally expressed gene delta-like homologue 1 (DLK1), forming an imprinting domain on chromosome
Words after: that contains two differentially methylated regions (DMRs), namely the intergenic DMR (IG-DMR) and post fertilization-derived secondary MEG3-DMR, as depicted in

File: pmc_10036404.txt, Loci: 14q32
Words before: maternally expressed gene mutually imprints with the paternally expressed gene delta-like homologue 1 (DLK1), forming an imprinting domain on chromosome
Words after: that contains two differentially methylated regions (DMRs), namely the intergenic DMR (IG-DMR) and post fertilization-derived secondary MEG3-DMR, as depicted in

File: pmc_10036404.txt, Loci: 14q32
Words before: maternally expressed gene mutually imprints with the paternally expressed gene delta-like homologue 1 (DLK1), forming an imprinting domain on chromosome
Words after: that contains two differentially methylated regions (DMRs), namely the intergenic DMR (IG-DMR) and post fertilization-derived secondary MEG3-DMR, as depicted in

File: pmc_10039029.txt, Loci: 6p21.33
Words before: the phase separation potential of mRNA Nature 2019 571 424 428 10.1038/s41586-019-1374-1 31292544 73. Jin G Low-frequency coding variants at
Words after: and 20q11.21 are associated with lung cancer risk in Chinese populations Am. J. Hum. Genet. 2015 96 832 840 10.1016/j.ajhg.2015.03.009

File: pmc_10039029.txt, Loci: 20q11.21
Words before: separation potential of mRNA Nature 2019 571 424 428 10.1038/s41586-019-1374-1 31292544 73. Jin G Low-frequency coding variants at 6p21.33 and
Words after: are associated with lung cancer risk in Chinese populations Am. J. Hum. Genet. 2015 96 832 840 10.1016/j.ajhg.2015.03.009 25937444 74.

File: pmc_10040244.txt, Loci: 6q23
Words before: causal variants within these gene deserts via their transcriptional effects in primary human CD4+ T cells. The authors investigated the
Words after: gene desert further because of its association with at least six immune-mediated diseases, highlighting the biological importance of this locus,

File: pmc_10040244.txt, Loci: 6q23
Words before: causal variants within these gene deserts via their transcriptional effects in primary human CD4+ T cells. The authors investigated the
Words after: gene desert further because of its association with at least six immune-mediated diseases, highlighting the biological importance of this locus,

File: pmc_10040244.txt, Loci: 6q23
Words before: causal variants within these gene deserts via their transcriptional effects in primary human CD4+ T cells. The authors investigated the
Words after: gene desert further because of its association with at least six immune-mediated diseases, highlighting the biological importance of this locus,

File: pmc_10040244.txt, Loci: 6q23
Words before: causal variants within these gene deserts via their transcriptional effects in primary human CD4+ T cells. The authors investigated the
Words after: gene desert further because of its association with at least six immune-mediated diseases, highlighting the biological importance of this locus,

File: pmc_10040244.txt, Loci: 6q23
Words before: causal variants within these gene deserts via their transcriptional effects in primary human CD4+ T cells. The authors investigated the
Words after: gene desert further because of its association with at least six immune-mediated diseases, highlighting the biological importance of this locus,

File: pmc_10040244.txt, Loci: 11q13.5
Words before: super-enhancer function and contribute directly to multiple diseases. LRRC32: an enhancer mediates the immunosuppressive activity of Treg cells Although the
Words after: locus is associated with allergic disease, inflammatory bowel disease and type 1 diabetes mellitus, its target gene and the mechanism

File: pmc_10040244.txt, Loci: 11q13.5
Words before: super-enhancer function and contribute directly to multiple diseases. LRRC32: an enhancer mediates the immunosuppressive activity of Treg cells Although the
Words after: locus is associated with allergic disease, inflammatory bowel disease and type 1 diabetes mellitus, its target gene and the mechanism

File: pmc_10040244.txt, Loci: 11q13
Words before: super-enhancer function and contribute directly to multiple diseases. LRRC32: an enhancer mediates the immunosuppressive activity of Treg cells Although the
Words after: locus is associated with allergic disease, inflammatory bowel disease and type 1 diabetes mellitus, its target gene and the mechanism

File: pmc_10040244.txt, Loci: 1p13
Words before: X., Li, H., Kuperwasser, N., Ruda, V. M. et al. (2010). From noncoding variant to phenotype via SORT1 at the
Words after: cholesterol locus. Nature 466, 714-719. 10.1038/nature0926620686566 Nasser, J., Bergman, D. T., Fulco, C. P., Guckelberger, P., Doughty, B. R., Patwardhan,

File: pmc_10040244.txt, Loci: 11q13.5
Words before: super-enhancer function and contribute directly to multiple diseases. LRRC32: an enhancer mediates the immunosuppressive activity of Treg cells Although the
Words after: locus is associated with allergic disease, inflammatory bowel disease and type 1 diabetes mellitus, its target gene and the mechanism

File: pmc_10046043.txt, Loci: 22q12.1
Words before: phenotypes and outcomes associated with most of these alterations have been poorly described. Checkpoint kinase 2 (CHEK2), located at chromosome
Words after: encodes a protein kinase that is activated by phosphorylation by the ATM protein in response to DNA damage. It serves

File: pmc_10046043.txt, Loci: 22q12.1
Words before: phenotypes and outcomes associated with most of these alterations have been poorly described. Checkpoint kinase 2 (CHEK2), located at chromosome
Words after: encodes a protein kinase that is activated by phosphorylation by the ATM protein in response to DNA damage. It serves

File: pmc_10046043.txt, Loci: 22q12.2
Words before: and loss of chromosome 22q. Notably, CHEK2 and NF2 map to chromosome 22, with CHEK2 at 22q12.1 and NF2 at
Words after: Inactivating alterations in NF2 with subsequent chromosome 22 loss is frequently described among meningiomas. Within this tumor, the deletion of

File: pmc_10046670.txt, Loci: 3p21.1
Words before: BrevetM. TaylorB.S. ShimizuS. ItoT. WangL. CreaneyJ. LakeR.A. ZakowskiM.F. RevaB. The nuclear deubiquitinase BAP1 is commonly inactivated by somatic mutations and
Words after: losses in malignant pleural mesothelioma Nat. Genet. 2011 43 668 672 10.1038/ng.855 21642991 44. GordonG.J. RockwellG.N. JensenR.V. RheinwaldJ.G. GlickmanJ.N. AronsonJ.P.

File: pmc_10049280.txt, Loci: 12p40
Words before: of TNF-α in monocytic THP1 cells stimulated with the TLR2 ligand Pam3CSK4 [151]. HnRNPU increases the expression of IL-8 and
Words after: by associating with ARE elements to regulate mRNA stability in a lncRNA FIRRE-dependent manner in LPS-stimulated macrophages [152]. HnRNPA2/B1 also

File: pmc_10052644.txt, Loci: 3p25
Words before: 8-oxoG, all organisms have developed several DNA repair strategies [8]. 8-Oxoguanine DNA glycosylase (encoded by the OGG1 gene on chromosome
Words after: is a key enzyme in correcting this mismatch. This multifunctional protein repairs the guanine lesions in mammalian cells through stepwise

File: pmc_10054671.txt, Loci: 9p21
Words before: 20541999 84. HoldtL.M. HoffmannS. SassK. LangenbergerD. ScholzM. KrohnK. FinstermeierK. StahringerA. WilfertW. BeutnerF. Alu elements in ANRIL non-coding RNA at chromosome
Words after: modulate atherogenic cell functions through trans-regulation of gene networks PLoS Genet. 2013 9 e1003588 10.1371/journal.pgen.1003588 23861667 85. TrendelJ. SchwarzlT. HorosR.

File: pmc_10062405.txt, Loci: 8p21.3
Words before: and associated behaviors (Hus et al., 2013; Sturm et al., 2017), were found in genome-wide significant linkage with loci at
Words after: and 8q24.22 (Lowe et al., 2015), supporting the validity of overall severity as a possible biologically based dimension within ASD.

File: pmc_10062405.txt, Loci: 8q24.22
Words before: behaviors (Hus et al., 2013; Sturm et al., 2017), were found in genome-wide significant linkage with loci at CHR8p21.3 and
Words after: (Lowe et al., 2015), supporting the validity of overall severity as a possible biologically based dimension within ASD. Lower sample

File: pmc_10062405.txt, Loci: 11q23
Words before: Kim et al., 2019a). For example, further fractionation of SC into a familial “joint attention” dimension demonstrated suggestive linkage at
Words after: (Liu et al., 2011), and use of “age at first word” as a QTL showed initial suggestive linkage at 7q35

File: pmc_10062405.txt, Loci: 7q35
Words before: 11q23 (Liu et al., 2011), and use of “age at first word” as a QTL showed initial suggestive linkage at

# 엑셀 파일로 저장

In [ ]:
import pandas as pd
import os
import re

def extract_context(text, loci, window_size=20):
    words = text.split()
    for i, word in enumerate(words):
        if loci in word:
            start = max(0, i - window_size)
            end = min(len(words), i + window_size + 1)
            return ' '.join(words[start:i]), ' '.join(words[i+1:end])
    return "", ""

text_folder_path = 'C:/Users/jhang/FullText_Epigenomics_data240126'  # Update this path
loci_pattern = re.compile(r'\d+[pq]\d+(\.\d+)?')
all_data = []

for file_name in os.listdir(text_folder_path):
    if file_name.endswith('.txt'):
        file_path = os.path.join(text_folder_path, file_name)
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()
            for match in loci_pattern.finditer(text):
                loci = match.group()
                before, after = extract_context(text, loci)
                all_data.append((file_name, loci, before, after))

df = pd.DataFrame(all_data, columns=['File Name', 'Loci', 'Words Before', 'Words After'])
#excel_file_path = 'C:/Users/User/extracted_loci_context(Words Before/After).xlsx'  # Update this path
#df.to_excel(excel_file_path, index=False)

# 데이터를 저장할 Excel 파일의 경로
excel_file_path = 'C:/Users/jhang/extracted_loci_context_240126(20 Words).xlsx'

# excel_file_path 저장된 파일 여부 확인
excel_dir = os.path.dirname(excel_file_path)
if not os.path.exists(excel_dir):
    os.makedirs(excel_dir)

# 데이터를 DataFrame으로 변환하여 Excel 파일에 저장
df = pd.DataFrame(all_data, columns=['File Name', 'Loci', 'Words Before', 'Words After'])
df.to_excel(excel_file_path, index=False)

print(f"Data saved to {excel_file_path}")

Data saved to C:/Users/jhang/extracted_loci_context_240126(20 Words).xlsx

# 저장한 excel file 확인

In [ ]:
import pandas as pd

# Excel 파일 경로
excel_file_path = 'C:/Users/jhang/extracted_loci_context_240126(20 Words).xlsx'
# Excel 파일 읽어와서 df에 저장
df = pd.read_excel(excel_file_path)

# Excel 파일 내용 확인
print("Contents of the Excel file:")
print(df)

Contents of the Excel file:
             File Name      Loci  \
0     pmc_10001080.txt  18q21.33
1     pmc_10006236.txt  12p13.33
2     pmc_10008685.txt   19p1036
3     pmc_10010017.txt   14q32.1
4     pmc_10010017.txt  14q32.31
...                ...       ...
5387   pmc_9997021.txt      1q21
5388   pmc_9997021.txt     17p13
5389   pmc_9997021.txt      1q21
5390   pmc_9997021.txt      1q21
5391   pmc_9997021.txt     17p13

                                           Words Before  \
0     enzyme used (regions of the CpG islands of the...
1     Proc. Natl. Acad. Sci. U. S. A. 2014 111 E645 ...
2     Biol Sci Int J Biol Sci ijbs International Jou...
3     piRNAs were upregulated (has-piR-010894-3 and ...
4     piRNAs were upregulated (has-piR-010894-3 and ...
...                                                 ...
5387  CNAs between cfDNA and BM was 67%. 12% and 21%...
5388  and BM was 67%. 12% and 21% of CNAs were BM-sp...
5389  CNAs between cfDNA and BM was 67%. 12% and 21%...
5390  CNAs between cfDNA and BM was 67%. 12% and 21%...
5391  and BM was 67%. 12% and 21% of CNAs were BM-sp...

                                            Words After
0     The DCs were selected from 5 genome regions, e...
1     including RAD52, influences the risk of squamo...
2     Review The Emerging Role of Super-enhancers as...
3     was related to the development of respiratory ...
4     was related to the development of respiratory ...
...                                                 ...
5387  gain and 17p13 deletion in cfDNA profiles were...
5388  deletion in cfDNA profiles were consistent wit...
5389  gain and 17p13 deletion in cfDNA profiles were...
5390  gain and 17p13 deletion in cfDNA profiles were...
5391  deletion in cfDNA profiles were consistent wit...

[5392 rows x 4 columns]

In [ ]:
df.head()

,File Name,Loci,Words Before,Words After
0,pmc_10001080.txt,18q21.33,enzyme used (regions of the CpG islands of the...,"The DCs were selected from 5 genome regions, e..."
1,pmc_10006236.txt,12p13.33,Proc. Natl. Acad. Sci. U. S. A. 2014 111 E645 ...,"including RAD52, influences the risk of squamo..."
2,pmc_10008685.txt,19p1036,Biol Sci Int J Biol Sci ijbs International Jou...,Review The Emerging Role of Super-enhancers as...
3,pmc_10010017.txt,14q32.1,piRNAs were upregulated (has-piR-010894-3 and ...,was related to the development of respiratory ...
4,pmc_10010017.txt,14q32.31,piRNAs were upregulated (has-piR-010894-3 and ...,was related to the development of respiratory ...

# loci_pattern(before/after) word를 stopwords 처리 후 추출

In [ ]:
import os
import re
import nltk
from nltk.corpus import stopwords

# stopwords 처리
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def extract_context(text, loci, window_size=20):
    words = text.split()
    for i, word in enumerate(words):
        if loci in word:
            start = max(0, i - window_size)
            end = min(len(words), i + window_size + 1)
            return words[start:i], words[i+1:end]
    return [], []

def filter_stopwords(words):
    return ' '.join([word for word in words if word.lower() not in stop_words])

# 데이터 파일 경로
text_folder_path = 'C:/Users/jhang/FullText_Epigenomics_data240126'

# loci_pattern의 패턴 지정
loci_pattern = re.compile(r'\d+[pq]\d+(\.\d+)?')

# 찾은 모든 위치, 파일 이름, 제목 및 컨텍스트 저장
all_data = []

for file_name in os.listdir(text_folder_path):
    # endswith() : 메서드 사용하여 어떤 문자열에서 특정 문자열로 끝나는지 확인 후, 그 결과 true 혹은 false 로 반환
    if file_name.endswith('.txt'):
        file_path = os.path.join(text_folder_path, file_name)
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()

            for match in loci_pattern.finditer(text):
                loci = match.group()
                before, after = extract_context(text, loci)
                before_filtered = filter_stopwords(before)
                after_filtered = filter_stopwords(after)
                all_data.append((file_name, loci, before_filtered, after_filtered))

# 찾은 file_name, loci, before, after 출력
for file_name, loci, before, after in all_data:
    print(f"File: {file_name}, Loci: {loci}")
    print(f"Words before (stopwords removed): {before}")
    print(f"Words after (stopwords removed): {after}\n")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jhang\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

File: pmc_10001080.txt, Loci: 18q21.33
Words before (stopwords removed): enzyme used (regions CpG islands SBNO2, LINC00493, CLDND1 genes intergenic CpG-island chromosome
Words after (stopwords removed): DCs selected 5 genome regions, containing 2 restriction enzyme recognition sites nonmethylated normal

File: pmc_10006236.txt, Loci: 12p13.33
Words before (stopwords removed): Proc. Natl. Acad. Sci. U. S. A. 2014 111 E645 654 10.1073/pnas.1312523111 24469817 66. Shi J Inherited variation chromosome
Words after (stopwords removed): including RAD52, influences risk squamous cell lung carcinoma Cancer Discov. 2012 2 131 139 10.1158/2159-8290.CD-11-0246 22585858 67. Ihsan

File: pmc_10008685.txt, Loci: 19p1036
Words before (stopwords removed): Biol Sci Int J Biol Sci ijbs International Journal Biological Sciences 1449-2288 Ivyspring International Publisher Sydney 36923930 10008685 10.7150/ijbs.78535
Words after (stopwords removed): Review Emerging Role Super-enhancers Therapeutic Targets Digestive System Tumors Li Xiang-Ping 1 2 * Qu

File: pmc_10010017.txt, Loci: 14q32.1
Words before (stopwords removed): piRNAs upregulated (has-piR-010894-3 has-piR-001168-4) [97]. Previous studies found dysregulation DLK1-DIO3 locus chromosomes
Words after (stopwords removed): related development respiratory tract diseases (including cancer). Katey SS Enfield et al. analyzed piRNAs encoded

File: pmc_10010017.txt, Loci: 14q32.31
Words before (stopwords removed): piRNAs upregulated (has-piR-010894-3 has-piR-001168-4) [97]. Previous studies found dysregulation DLK1-DIO3 locus chromosomes
Words after (stopwords removed): related development respiratory tract diseases (including cancer). Katey SS Enfield et al. analyzed piRNAs encoded

File: pmc_10011137.txt, Loci: 1q45
Words before (stopwords removed): 30https://ror.org/03zzw1w08grid.417467.70000 0004 0443 9942Division Respiratory Medicine, Department Internal Medicine, Center Individualized Medicine, Mayo Clinic, Scottsdale, AZ USA
Words after (stopwords removed): 0001 2168 186XDepartment Medicine, University Arizona, Tucson, AZ USA 32https://ror.org/05a0ya142grid.66859.34Broad Institute MIT Harvard, Cambridge, USA

File: pmc_10011137.txt, Loci: 415q13
Words before (stopwords removed): Institute, Newcastle, New South Wales Australia 78https://ror.org/01dbmzx78grid.414659.b0000 0000 8828 1230Wal-yan Respiratory Research Centre, Telethon Kids Institute, Perth, Western Australia Australia
Words after (stopwords removed): 0004 0375 4078School Allied Health, Faculty Health Sciences, Curtin University, Perth, Western Australia Australia 80https://ror.org/01nrxwf90grid.4305.20000 0004 1936 7988Lothian

File: pmc_10012557.txt, Loci: 12p70
Words before (stopwords removed): Deauvieau F Scuiller Hiscott J Bates EE type interferon autocrine-paracrine loop involved toll-like receptor-induced
Words after (stopwords removed): secretion dendritic cells J Exp Med 2005 201 9 1435 46 10.1084/jem.20041964 15851485 57. Lee AJ Ashkar AA

File: pmc_10014551.txt, Loci: 22q11.2
Words before (stopwords removed): Prader-Willi syndrome, Williams syndrome, Fragile X syndrome, Angelman’s syndrome, Cri de Chat syndrome, syndrome, Lowe syndrome, Smith-Magenis, PTEN mutations,
Words after (stopwords removed): deletion syndrome, obsessive compulsive disorder (OCD), Tic disorders, eating disorders, psychotic disorders, Attention deficit hyperactivity disorder (ADHD), RRBs often form

File: pmc_10014551.txt, Loci: 22q11.2
Words before (stopwords removed): Prader-Willi syndrome, Williams syndrome, Fragile X syndrome, Angelman’s syndrome, Cri de Chat syndrome, syndrome, Lowe syndrome, Smith-Magenis, PTEN mutations,
Words after (stopwords removed): deletion syndrome, obsessive compulsive disorder (OCD), Tic disorders, eating disorders, psychotic disorders, Attention deficit hyperactivity disorder (ADHD), RRBs often form

File: pmc_10014551.txt, Loci: 22q11.2
Words before (stopwords removed): Prader-Willi syndrome, Williams syndrome, Fragile X syndrome, Angelman’s syndrome, Cri de Chat syndrome, syndrome, Lowe syndrome, Smith-Magenis, PTEN mutations,
Words after (stopwords removed): deletion syndrome, obsessive compulsive disorder (OCD), Tic disorders, eating disorders, psychotic disorders, Attention deficit hyperactivity disorder (ADHD), RRBs often form

File: pmc_10014730.txt, Loci: 7q35
Words before (stopwords removed): 5333361. 10.1155/2023/5333361 36644165 IsobeM.EriksonJ.EmanuelB. S.NowellP. C.CroceC. M. (1985). Location gene beta subunit human T-cell receptor band
Words after (stopwords removed): region prone rearrangements cells. Science 228, 580–582. 10.1126/science.3983641 3983641 KeG.MengQ.FinleyT.WangT.ChenW.MaW. (2017). Lightgbm: highly efficient gradient

File: pmc_10018228.txt, Loci: 8q24.21
Words before (stopwords removed): gains losses associated high grade, Gleason score, PSA levels (47). Common amplifications span oncogenes MYC
Words after (stopwords removed): CCND1 (11q13.2), FCFR (12p11.21), NSD3 (8p11.23) common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1),

File: pmc_10018228.txt, Loci: 11q13.2
Words before (stopwords removed): losses associated high grade, Gleason score, PSA levels (47). Common amplifications span oncogenes MYC (8q24.21), CCND1
Words after (stopwords removed): FCFR (12p11.21), NSD3 (8p11.23) common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2

File: pmc_10018228.txt, Loci: 12p11.21
Words before (stopwords removed): associated high grade, Gleason score, PSA levels (47). Common amplifications span oncogenes MYC (8q24.21), CCND1 (11q13.2), FCFR
Words after (stopwords removed): NSD3 (8p11.23) common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22),

File: pmc_10018228.txt, Loci: 8p11.23
Words before (stopwords removed): grade, Gleason score, PSA levels (47). Common amplifications span oncogenes MYC (8q24.21), CCND1 (11q13.2), FCFR (12p11.21), NSD3
Words after (stopwords removed): common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL

File: pmc_10018228.txt, Loci: 10q23
Words before (stopwords removed): span oncogenes MYC (8q24.21), CCND1 (11q13.2), FCFR (12p11.21), NSD3 (8p11.23) common deletions span tumor suppressor genes PTEN
Words after (stopwords removed): TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors

File: pmc_10018228.txt, Loci: 17p13.1
Words before (stopwords removed): oncogenes MYC (8q24.21), CCND1 (11q13.2), FCFR (12p11.21), NSD3 (8p11.23) common deletions span tumor suppressor genes PTEN (10q23), TP53
Words after (stopwords removed): CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors greater

File: pmc_10018228.txt, Loci: 12p13.1
Words before (stopwords removed): (8q24.21), CCND1 (11q13.2), FCFR (12p11.21), NSD3 (8p11.23) common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B
Words after (stopwords removed): MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors greater mutational burden

File: pmc_10018228.txt, Loci: 5q11.2
Words before (stopwords removed): (11q13.2), FCFR (12p11.21), NSD3 (8p11.23) common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1
Words after (stopwords removed): & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors greater mutational burden

File: pmc_10018228.txt, Loci: 3p26
Words before (stopwords removed): NSD3 (8p11.23) common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2
Words after (stopwords removed): SPOPL (2q22.1), FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors greater mutational burden higher CNA frequencies

File: pmc_10018228.txt, Loci: 2q22.1
Words before (stopwords removed): common deletions span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL
Words after (stopwords removed): FOXP1/RYBP/SHQ1 (3p13) (47). Interestingly, aggressive prostate tumors greater mutational burden higher CNA frequencies mutations

File: pmc_10018228.txt, Loci: 3p13
Words before (stopwords removed): span tumor suppressor genes PTEN (10q23), TP53 (17p13.1), CDKN1B (12p13.1), MAP3K1 (5q11.2 & 6q.12-22), FANCD2 (3p26), SPOPL (2q22.1), FOXP1/RYBP/SHQ1
Words after (stopwords removed): (47). Interestingly, aggressive prostate tumors greater mutational burden higher CNA frequencies mutations KMT2D, TP53,

File: pmc_10018228.txt, Loci: 1q23.1
Words before (stopwords removed): cell growth survival, DNA replication, respectively. study Koga et al. identified novel deletion spanning ETV3
Words after (stopwords removed): another ETS transcription factor, AA tumor samples (13). Overall, studies addressing racial differences

File: pmc_10023161.txt, Loci: 5q31
Words before (stopwords removed): JacksonCE BeckmannJS SebounE 1998 Vocal cord pharyngeal weakness autosomal dominant distal myopathy: clinical description gene localization
Words after (stopwords removed): American Journal Human Genetics 63 1732 1742 10.1086/302166 9837826 FrancoD MeilhacSM ChristoffelsVM KispertA BuckinghamM KellyRG 2006 Left right

File: pmc_10023161.txt, Loci: 5q31
Words before (stopwords removed): JacksonCE BeckmannJS SebounE 1998 Vocal cord pharyngeal weakness autosomal dominant distal myopathy: clinical description gene localization
Words after (stopwords removed): American Journal Human Genetics 63 1732 1742 10.1086/302166 9837826 FrancoD MeilhacSM ChristoffelsVM KispertA BuckinghamM KellyRG 2006 Left right

File: pmc_10026484.txt, Loci: 1p1
Words before (stopwords removed): confirm presence expected BCL7A mutations RNA level. Read counts per gene obtained using htseq-count
Words after (stopwords removed): following options: “-m intersection-nonempty -f bam -t exon -i gene_id -r pos -s reverse”. analyses performed

File: pmc_10036404.txt, Loci: 14q32
Words before (stopwords removed): maternally expressed gene mutually imprints paternally expressed gene delta-like homologue 1 (DLK1), forming imprinting domain chromosome
Words after (stopwords removed): contains two differentially methylated regions (DMRs), namely intergenic DMR (IG-DMR) post fertilization-derived secondary MEG3-DMR, depicted

File: pmc_10036404.txt, Loci: 14q32
Words before (stopwords removed): maternally expressed gene mutually imprints paternally expressed gene delta-like homologue 1 (DLK1), forming imprinting domain chromosome
Words after (stopwords removed): contains two differentially methylated regions (DMRs), namely intergenic DMR (IG-DMR) post fertilization-derived secondary MEG3-DMR, depicted

File: pmc_10036404.txt, Loci: 14q32
Words before (stopwords removed): maternally expressed gene mutually imprints paternally expressed gene delta-like homologue 1 (DLK1), forming imprinting domain chromosome
Words after (stopwords removed): contains two differentially methylated regions (DMRs), namely intergenic DMR (IG-DMR) post fertilization-derived secondary MEG3-DMR, depicted

File: pmc_10036404.txt, Loci: 14q32
Words before (stopwords removed): maternally expressed gene mutually imprints paternally expressed gene delta-like homologue 1 (DLK1), forming imprinting domain chromosome
Words after (stopwords removed): contains two differentially methylated regions (DMRs), namely intergenic DMR (IG-DMR) post fertilization-derived secondary MEG3-DMR, depicted

File: pmc_10036404.txt, Loci: 14q32
Words before (stopwords removed): maternally expressed gene mutually imprints paternally expressed gene delta-like homologue 1 (DLK1), forming imprinting domain chromosome
Words after (stopwords removed): contains two differentially methylated regions (DMRs), namely intergenic DMR (IG-DMR) post fertilization-derived secondary MEG3-DMR, depicted

File: pmc_10036404.txt, Loci: 14q32
Words before (stopwords removed): maternally expressed gene mutually imprints paternally expressed gene delta-like homologue 1 (DLK1), forming imprinting domain chromosome
Words after (stopwords removed): contains two differentially methylated regions (DMRs), namely intergenic DMR (IG-DMR) post fertilization-derived secondary MEG3-DMR, depicted

File: pmc_10039029.txt, Loci: 6p21.33
Words before (stopwords removed): phase separation potential mRNA Nature 2019 571 424 428 10.1038/s41586-019-1374-1 31292544 73. Jin G Low-frequency coding variants
Words after (stopwords removed): 20q11.21 associated lung cancer risk Chinese populations Am. J. Hum. Genet. 2015 96 832 840 10.1016/j.ajhg.2015.03.009

File: pmc_10039029.txt, Loci: 20q11.21
Words before (stopwords removed): separation potential mRNA Nature 2019 571 424 428 10.1038/s41586-019-1374-1 31292544 73. Jin G Low-frequency coding variants 6p21.33
Words after (stopwords removed): associated lung cancer risk Chinese populations Am. J. Hum. Genet. 2015 96 832 840 10.1016/j.ajhg.2015.03.009 25937444 74.

File: pmc_10040244.txt, Loci: 6q23
Words before (stopwords removed): causal variants within gene deserts via transcriptional effects primary human CD4+ cells. authors investigated
Words after (stopwords removed): gene desert association least six immune-mediated diseases, highlighting biological importance locus,

File: pmc_10040244.txt, Loci: 6q23
Words before (stopwords removed): causal variants within gene deserts via transcriptional effects primary human CD4+ cells. authors investigated
Words after (stopwords removed): gene desert association least six immune-mediated diseases, highlighting biological importance locus,

File: pmc_10040244.txt, Loci: 6q23
Words before (stopwords removed): causal variants within gene deserts via transcriptional effects primary human CD4+ cells. authors investigated
Words after (stopwords removed): gene desert association least six immune-mediated diseases, highlighting biological importance locus,

File: pmc_10040244.txt, Loci: 6q23
Words before (stopwords removed): causal variants within gene deserts via transcriptional effects primary human CD4+ cells. authors investigated
Words after (stopwords removed): gene desert association least six immune-mediated diseases, highlighting biological importance locus,

File: pmc_10040244.txt, Loci: 6q23
Words before (stopwords removed): causal variants within gene deserts via transcriptional effects primary human CD4+ cells. authors investigated
Words after (stopwords removed): gene desert association least six immune-mediated diseases, highlighting biological importance locus,

File: pmc_10040244.txt, Loci: 11q13.5
Words before (stopwords removed): super-enhancer function contribute directly multiple diseases. LRRC32: enhancer mediates immunosuppressive activity Treg cells Although
Words after (stopwords removed): locus associated allergic disease, inflammatory bowel disease type 1 diabetes mellitus, target gene mechanism

File: pmc_10040244.txt, Loci: 11q13.5
Words before (stopwords removed): super-enhancer function contribute directly multiple diseases. LRRC32: enhancer mediates immunosuppressive activity Treg cells Although
Words after (stopwords removed): locus associated allergic disease, inflammatory bowel disease type 1 diabetes mellitus, target gene mechanism

File: pmc_10040244.txt, Loci: 11q13
Words before (stopwords removed): super-enhancer function contribute directly multiple diseases. LRRC32: enhancer mediates immunosuppressive activity Treg cells Although
Words after (stopwords removed): locus associated allergic disease, inflammatory bowel disease type 1 diabetes mellitus, target gene mechanism

File: pmc_10040244.txt, Loci: 1p13
Words before (stopwords removed): X., Li, H., Kuperwasser, N., Ruda, V. M. et al. (2010). noncoding variant phenotype via SORT1
Words after (stopwords removed): cholesterol locus. Nature 466, 714-719. 10.1038/nature0926620686566 Nasser, J., Bergman, D. T., Fulco, C. P., Guckelberger, P., Doughty, B. R., Patwardhan,

File: pmc_10040244.txt, Loci: 11q13.5
Words before (stopwords removed): super-enhancer function contribute directly multiple diseases. LRRC32: enhancer mediates immunosuppressive activity Treg cells Although
Words after (stopwords removed): locus associated allergic disease, inflammatory bowel disease type 1 diabetes mellitus, target gene mechanism

File: pmc_10046043.txt, Loci: 22q12.1
Words before (stopwords removed): phenotypes outcomes associated alterations poorly described. Checkpoint kinase 2 (CHEK2), located chromosome
Words after (stopwords removed): encodes protein kinase activated phosphorylation ATM protein response DNA damage. serves

File: pmc_10046043.txt, Loci: 22q12.1
Words before (stopwords removed): phenotypes outcomes associated alterations poorly described. Checkpoint kinase 2 (CHEK2), located chromosome
Words after (stopwords removed): encodes protein kinase activated phosphorylation ATM protein response DNA damage. serves

File: pmc_10046043.txt, Loci: 22q12.2
Words before (stopwords removed): loss chromosome 22q. Notably, CHEK2 NF2 map chromosome 22, CHEK2 22q12.1 NF2
Words after (stopwords removed): Inactivating alterations NF2 subsequent chromosome 22 loss frequently described among meningiomas. Within tumor, deletion

File: pmc_10046670.txt, Loci: 3p21.1
Words before (stopwords removed): BrevetM. TaylorB.S. ShimizuS. ItoT. WangL. CreaneyJ. LakeR.A. ZakowskiM.F. RevaB. nuclear deubiquitinase BAP1 commonly inactivated somatic mutations
Words after (stopwords removed): losses malignant pleural mesothelioma Nat. Genet. 2011 43 668 672 10.1038/ng.855 21642991 44. GordonG.J. RockwellG.N. JensenR.V. RheinwaldJ.G. GlickmanJ.N. AronsonJ.P.

File: pmc_10049280.txt, Loci: 12p40
Words before (stopwords removed): TNF-α monocytic THP1 cells stimulated TLR2 ligand Pam3CSK4 [151]. HnRNPU increases expression IL-8
Words after (stopwords removed): associating elements regulate mRNA stability lncRNA FIRRE-dependent manner LPS-stimulated macrophages [152]. HnRNPA2/B1 also

File: pmc_10052644.txt, Loci: 3p25
Words before (stopwords removed): 8-oxoG, organisms developed several DNA repair strategies [8]. 8-Oxoguanine DNA glycosylase (encoded OGG1 gene chromosome
Words after (stopwords removed): key enzyme correcting mismatch. multifunctional protein repairs guanine lesions mammalian cells stepwise

File: pmc_10054671.txt, Loci: 9p21
Words before (stopwords removed): 20541999 84. HoldtL.M. HoffmannS. SassK. LangenbergerD. ScholzM. KrohnK. FinstermeierK. StahringerA. WilfertW. BeutnerF. Alu elements ANRIL non-coding RNA chromosome
Words after (stopwords removed): modulate atherogenic cell functions trans-regulation gene networks PLoS Genet. 2013 9 e1003588 10.1371/journal.pgen.1003588 23861667 85. TrendelJ. SchwarzlT. HorosR.

File: pmc_10062405.txt, Loci: 8p21.3
Words before (stopwords removed): associated behaviors (Hus et al., 2013; Sturm et al., 2017), found genome-wide significant linkage loci
Words after (stopwords removed): 8q24.22 (Lowe et al., 2015), supporting validity overall severity possible biologically based dimension within ASD.

File: pmc_10062405.txt, Loci: 8q24.22
Words before (stopwords removed): behaviors (Hus et al., 2013; Sturm et al., 2017), found genome-wide significant linkage loci CHR8p21.3
Words after (stopwords removed): (Lowe et al., 2015), supporting validity overall severity possible biologically based dimension within ASD. Lower sample

File: pmc_10062405.txt, Loci: 11q23
Words before (stopwords removed): Kim et al., 2019a). example, fractionation SC familial “joint attention” dimension demonstrated suggestive linkage

# 엑셀 파일로 저장

In [ ]:
import os
import re
import nltk
import pandas as pd
from nltk.corpus import stopwords

# NLTK stopwords 다운로드
nltk.download('stopwords')

# Set stopwords 처리
stop_words = set(stopwords.words('english'))

def extract_context(text, loci, window_size=20):
    words = text.split()
    for i, word in enumerate(words):
        if loci in word:
            start = max(0, i - window_size)
            end = min(len(words), i + window_size + 1)
            return words[start:i], words[i+1:end]
    return [], []

def filter_stopwords(words):
    return ' '.join([word for word in words if word.lower() not in stop_words])

# 데이터 파일 경로
text_folder_path = 'C:/Users/jhang/FullText_Epigenomics_data240126'

# loci_pattern의 패턴 지정
loci_pattern = re.compile(r'\d+[pq]\d+(\.\d+)?')

# 찾은 모든 위치, 파일 이름, 제목 및 컨텍스트 저장
all_data = []

for file_name in os.listdir(text_folder_path):
    # endswith() : 메서드 사용하여 어떤 문자열에서 특정 문자열로 끝나는지 확인 후, 그 결과 true 혹은 false 로 반환
    if file_name.endswith('.txt'):
        file_path = os.path.join(text_folder_path, file_name)
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()

            for match in loci_pattern.finditer(text):
                loci = match.group()
                before, after = extract_context(text, loci)
                before_filtered = filter_stopwords(before)
                after_filtered = filter_stopwords(after)
                all_data.append((file_name, loci, before_filtered, after_filtered))

# 데이터를 DataFrame으로 변환
df = pd.DataFrame(all_data, columns=['File Name', 'Loci', 'Words Before (No Stopwords)', 'Words After (No Stopwords)'])

# 데이터를 저장할 Excel 파일의 경로
excel_file_path = 'C:/Users/jhang/extracted_loci_context(No Stopwords제외)_240126(20 Words).xlsx'

# Excel file 저장
df.to_excel(excel_file_path, index=False)

print(f"Data saved to {excel_file_path}")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jhang\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Data saved to C:/Users/jhang/extracted_loci_context(No Stopwords제외)_240126(20 Words).xlsx

# 저장한 excel file 확인

In [ ]:
import pandas as pd

# Excel 파일 경로
excel_file_path = 'C:/Users/jhang/extracted_loci_context(No Stopwords제외)_240126(20 Words).xlsx'
# Excel 파일 읽어와서 df에 저장
df = pd.read_excel(excel_file_path)

# Excel 파일 내용 확인
print("Contents of the Excel file:")
print(df)

Contents of the Excel file:
             File Name      Loci  \
0     pmc_10001080.txt  18q21.33
1     pmc_10006236.txt  12p13.33
2     pmc_10008685.txt   19p1036
3     pmc_10010017.txt   14q32.1
4     pmc_10010017.txt  14q32.31
...                ...       ...
5387   pmc_9997021.txt      1q21
5388   pmc_9997021.txt     17p13
5389   pmc_9997021.txt      1q21
5390   pmc_9997021.txt      1q21
5391   pmc_9997021.txt     17p13

                            Words Before (No Stopwords)  \
0     enzyme used (regions CpG islands SBNO2, LINC00...
1     Proc. Natl. Acad. Sci. U. S. A. 2014 111 E645 ...
2     Biol Sci Int J Biol Sci ijbs International Jou...
3     piRNAs upregulated (has-piR-010894-3 has-piR-0...
4     piRNAs upregulated (has-piR-010894-3 has-piR-0...
...                                                 ...
5387  CNAs cfDNA BM 67%. 12% 21% CNAs BM-specific cf...
5388  BM 67%. 12% 21% CNAs BM-specific cfDNA-specifi...
5389  CNAs cfDNA BM 67%. 12% 21% CNAs BM-specific cf...
5390  CNAs cfDNA BM 67%. 12% 21% CNAs BM-specific cf...
5391  BM 67%. 12% 21% CNAs BM-specific cfDNA-specifi...

                             Words After (No Stopwords)
0     DCs selected 5 genome regions, containing 2 re...
1     including RAD52, influences risk squamous cell...
2     Review Emerging Role Super-enhancers Therapeut...
3     related development respiratory tract diseases...
4     related development respiratory tract diseases...
...                                                 ...
5387  gain 17p13 deletion cfDNA profiles consistent ...
5388  deletion cfDNA profiles consistent results BM ...
5389  gain 17p13 deletion cfDNA profiles consistent ...
5390  gain 17p13 deletion cfDNA profiles consistent ...
5391  deletion cfDNA profiles consistent results BM ...

[5392 rows x 4 columns]

In [ ]:
df.head()

,File Name,Loci,Words Before (No Stopwords),Words After (No Stopwords)
0,pmc_10001080.txt,18q21.33,"enzyme used (regions CpG islands SBNO2, LINC00...","DCs selected 5 genome regions, containing 2 re..."
1,pmc_10006236.txt,12p13.33,Proc. Natl. Acad. Sci. U. S. A. 2014 111 E645 ...,"including RAD52, influences risk squamous cell..."
2,pmc_10008685.txt,19p1036,Biol Sci Int J Biol Sci ijbs International Jou...,Review Emerging Role Super-enhancers Therapeut...
3,pmc_10010017.txt,14q32.1,piRNAs upregulated (has-piR-010894-3 has-piR-0...,related development respiratory tract diseases...
4,pmc_10010017.txt,14q32.31,piRNAs upregulated (has-piR-010894-3 has-piR-0...,related development respiratory tract diseases...